services:
  frontend:
    build: .
    container_name: HomePage
    ports:
      - "4200:80"
    volumes:
      - .:/app:Z
      - node_modules:/app/node_modules:Z
    environment:
      - NODE_ENV=development

volumes:
  node_modules:
